name: CD2-Sync Docker Build

on:
  # 自动触发：当推送 tag 时 (如 v1.0.0)
  push:
    tags:
      - "*"

  # 手动触发
  workflow_dispatch:
    inputs:
      tags:
        description: '镜像标签 (如: latest, v1.0.0)'
        required: true
        default: 'latest'
      push:
        description: '是否推送到镜像仓库'
        required: true
        type: boolean
        default: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Tag and Push Status
        id: config
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag_name=${{ inputs.tags }}" >> $GITHUB_OUTPUT
            echo "should_push=${{ inputs.push }}" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
            echo "should_push=true" >> $GITHUB_OUTPUT
          fi

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # ⚠️ 修改为你的 Docker Hub 用户名/镜像名
          images: |
            lfy1680/cd2-sync
          tags: |
            type=raw,value=${{ steps.config.outputs.tag_name }}
            type=raw,value=latest,enable=${{ github.ref_type == 'tag' }}

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
          #  linux/arm64
          push: ${{ steps.config.outputs.should_push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
